export class Incapacidad {
    estado:string;
    estadoObservacion:string;
    estadoObservacionTrabajador:string;
    fechaInicial:string;
    fechaFinal:string;
    fechaRadicacion:string;
    incapacidadDescripcion:string;
    nombreDelEmpleado:string;
    nombreEmpresa:string;
    nombreEps:number;
    numeroContrato:number;
    numeroDeDias:string;
    numeroDocumentoEmpleado:number;
    numeroRadicado:number;
    subTipoIncapacidad:string;
    subTipoIncapacidadCodigo:number;
    tipoDocumentoEmpleado:string;
    tipoIncapacidad:string;
}
